server:
  port: 8909
security:
  basic:
    enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://192.168.0.20:8761/eureka
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@orcl.chkv5c8s1oal.us-east-1.rds.amazonaws.com:1521:orcl
    username: HydraTrainee
    password: momonga
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: 35.183.27.227
    port: 5672
    username: guest
    password: guest
  application:
    name: user-service
